apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: activity-tracker
spec:
  serviceName: mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: activity-tracker
      component: mongo
  template:
    metadata:
      labels:
        app: activity-tracker
        component: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: activity-tracker
spec:
  clusterIP: None
  selector:
    app: activity-tracker
    component: mongo
  ports:
    - port: 27017
      targetPort: 27017
